michal-h21/biblatex-iso690

- iso-numeric.bbx
Given the upcoming changes in `biblatex` 3.4 https://github.com/plk/biblatex/releases/tag/v3.4 we now need to print `labelprefix` and not `prefixnumber`. The change retains backwards compatibility and can be applied before biblatex 3.4 goes live.
> Use `labelprefix` and not `prefixnumber`

- iso.bbx
"In" macro defined in `iso.bbx` seems to be redundant since "in:" macro defined in `biblatex.def` exists.
> Use default biblatex `in` macro.

- iso.bbx
According to ISO 690:2011, following changes are required:
* as a rule of thumb, all of the creators' names should be given if possible. In the case any names are omitted, the norm exclusively states that
> the name of the first creator shall be given followed by “and others” or “et al.”.
Let's assume the threshold of `maxnames` option to be nine.
* I can not manage to find exclusively stated in the norm the second point about **_and_** delimiter before the final name in a name list, but all of the examples provided there show it in this way. Hence I propose this change here.
> Multiple creators -- final name 'and' delimiter; first creator + et al.

- iso-authoryear.bbx
- iso.bbx
Some cleanup of respective bibmacros + removing unused macro journal-year.
According to the ISO 690 norm, there is still one issue -- when printing date which has open-ended range, first year should be followed by a dash and space. Now it is without that space. Due to the biblatex features etc. I was not able to hack it in the way to print the ending space there. Any ideas how to achieve this?
BTW, I would say `\bibdatedash` defined in `czech.lbx` should use `\textendash` instead of `\textemdash`. But I may be wrong.
> Date + urldate macros

- iso.bbx
Even though the number of total pages when citing the work as a whole is no longer required part of a bibliography entry, better support for it would be welcome. Mainly because totalpages field could be printed at the end of bibliography as an optional element. I have tried out to place it in the square brackets there, but it doesn't look 'nice' there in this way, mainly due the 'custom' from past. Hence now it is proposed without printing number of total pages anywhere.
> Total pages

- README
- bibpok.tex
- iso-example.tex
- iso.bbx
The `babel` option is kept around for backwards compatibility, but it is deprecated (emits warnings).
> The `babel` option was changed to `autolang` in BibLaTeX 2.8.

- iso.bbx
Introduced in #35 comments, macro for the numeration stuff would be great deal. I've just collected there respective field, i.e. volume, number and chapter (in this order) which are mostly used.
The field pages is not included there, because the norm itself deals with this element separately as well.
> Macro numeration for handling the respective stuff.

- bibpok.tex
- iso-authoryear.bbx
- iso-example.tex
- iso.bbx
\bibliography command is still available for backwards compatibility, but it is deprecated.
> \bibliography superseded by \addbibresource in BibLaTeX 1.2

- czech-iso.lbx
- english-iso.lbx
- iso.bbx
Well, stuff regarding availability of resources needed better handling, i.e.
* `urlfrom` and `urlalso` differentiation on more proper place,
* doi or eprint identifiers takes precedence over url address (according the norm)
* I do not exactly know why there was so robust testing on `url`, `doi` and `eprint` fields, hence I have just commented respective macros out, not deleting them
* I have redeclared just `doi` field (and just a little bit) and not also `eprint`, because `eprint` default handling is really nice, imho
* correction of `howpublished` field as a type of medium, because it was not working properly
* and defining one macro for all standard identifiers available by biblatex package
* I am not sure I understand how the handling of multiple ISSNs works, because I suppose if …
> Url + type of medium + identifiers

- iso.bbx
This could be the best resolution of all of the problems regarding the multilingual stuff, thanks to the section 10.3 of the norm
> The term “volume” and terms for smaller components of a serial publication may be omitted and the numbers distinguished typographically, with the volume number in bold type and the part number, if required, in parentheses.
It's set to be the default option for handling numeration stuff.
> Omission of numeration and pagination terms.

- iso.bbx
Titles related macros needed refactoring as well, so here it is:
* macro `pub:title` handled some checking on `maintitle` and `booktitle`, which was causing problems e.g. with `knuth:ct` works (addressing #19 -- [at the end of this comment](https://github.com/michal-h21/biblatex-iso690/issues/19#issuecomment-139738188))
* according the norm and the basic principle of determining the appropriate level of specificity at which the reference is made, the `maintitle` or `booktitle` is not worth to print if it is related to `@book` entry type. Hence `title` is enough.
* `pub:title` has been renamed to `host:titles` and rewritten to be applied to use for printing host item (book, collection, etc.) of the reference.
* `medium-type` macro has been extracted as a separate macro into the drivers
* …
> Titles refactoring

- iso-numeric.bbx
The `iso-numeric` bibliography style has the labels hanging into the left margin. I think it would be better to not have the labels hang by default, as is tends to look out of place in most documents:
If changing the style is not an option, then I suggest adding an FAQ entry into the manual as I imagine this will be a show-stopper for many potential users.
> Make numeric bibliography style visually compatible with non-iso styles.

- iso.bbx
This adds support for the biblatex style options for showing/hiding the `ISBN`, `url`, `DOI` and `eprint` fields. It would be nice to also support this as the default styles support it, see biblatex package docs section "3.1.2.2 Style-specific"
> Add support for biblatex style options.

- iso.bbx
Section 2.5.2.2 of the DOI® Handbook favors usage of https:// protocol over http:// and doi.org address over dx.doi.org in URLs.
> Use DOI-preferred URL format for links

- bulgarian-iso.lbx
I can translate `director` and `bydirector` if I know in what context they are used. I could not find this information on the internet.
> Add missing bg translation.

- bulgarian-iso.lbx
- czech-iso.lbx
- english-iso.lbx
- french-iso.lbx
- german-iso.lbx
- iso-authoryear.bbx
- iso.bbx
- polish-iso.lbx
- slovak-iso.lbx
- spanish-iso.lbx
Hi!
I improved the @patent entry type according to the description in the "DIN ISO 690:2013-10" (the German version of the norm) by having a closer look at the few examples.
Here is an example taken from the iso document itself to illustrate how we can create patent entries from now on.
```
@patent{winget,
holder          = {{Winget Ltd}},
title           = {Detachable bulldozer attachment for dumper vehicles},
number          = {1060631},
date            = {1967-03-08},
author          = {Reginald John England},
origdate        = {1963-06-10},
note            = {Int\adddotspace CI\addcolon\addabbrvspace E02F 3/76\adddotspace
GB\addabbrvspace CI\addcolon\addabbrvspace E1F 12},
type            = {patentuk},
langid          = {english}
}
```
Note that the `holder` field becomes the primary …
> Improvement of @patent entry type.

- iso.bbx
This will make the names of the author to be in the right order for the @patent entrytype if the user only makes use of the author filed.
> Always right order of author names in @patent

- iso.bbx
As already discussed in the PR #99, I replaced `\printfield{note}` with `\printfield{addendum}` according to the biblatex documentation:
> note field (literal)
> Miscellaneous bibliographic data which does not fit into any other field. The note
> field may be used to record bibliographic data in a free format. Publication facts such
> as “Reprint of the edition London 1831” are typical candidates for the note field.
> See also addendum.
> addendum field (literal)
> Miscellaneous bibliographic data to be printed at the end of the entry. This is similar
> to the note field except that it is printed at the end of the bibliography entry.
> Replacement: addendum -> notes

- bulgarian-iso.lbx
- czech-iso.lbx
- english-iso.lbx
- french-iso.lbx
- german-iso.lbx
- iso-alphabetic.dbx
- iso-authortitle.dbx
- iso-authoryear.dbx
- iso-numeric.dbx
- iso.bbx
- polish-iso.lbx
- slovak-iso.lbx
- spanish-iso.lbx
I added the identifiers eisbn, eissn, lccn and din.
Moreover I added the bibstrings `urlfrom`, `urlseen` and `andothers` to those languages where the were not already defined anyway. Of course, I did not dare to translate other languages here. For german and english I just took the exact expression as given in the corresponding iso 690 document.
I also took a very close look at the punctuation and made it exactly the same as given in the iso 690 document.
> Improvement: Identifiers

- iso.bbx
I extented the definition of the FielFormat for `url` such that it is now compatible with my last adjustment (see PR #108) of how the `doi` identifier is displayed.
> Improvement: url FieldFormat extented

- iso.bbx
Very similar to PR #112 I created a new package option `bibacrosc` so that one can now decide wether to print the bib acronyms such as `ISBN` as textsc or simply the way they are written.
> New Package Option: bibacrosc

- biblatex-iso690-examples.bib
- bulgarian-iso.lbx
- czech-iso.lbx
- english-iso.lbx
- french-iso.lbx
- german-iso.lbx
- iso-authoryear.bbx
- iso.bbx
- polish-iso.lbx
- slovak-iso.lbx
- spanish-iso.lbx
According to section 8.2 of the ISO 690-2010, I added a new bibmacro called `refreshdate`.
Moreover I made it possible to add a copyright symbol in front of the date. The example given in the document in that section can now be realised as follows:
```
@manual{idoifoundation,
editor          = {{International DOI Foundation}},
title           = {DOI Handbook},
origdate        = {2006},
origdate+an     = {=copyright},
type            = {online},
date            = {2007-09-19},
urldate         = {2008-05-20},
url             = {http://www.doi.org/hb.html},
langid          = {english}
}
```
Note that, similar to the patent entrytype, the `origdate` field becomes the primary date here and the `date` field is used as the refresh date. The copyright symbol is implemented by using data field …
> Extension: New bibmacro refreshdate + copyrightsymbol

- biblatex-iso690-examples.bib
- iso.bbx
I improved the thesis entrytype.
With the old version of the norm (ISO 690:2010(E)) it was always unclear how to corretly print a thesis bibliography entry because there was no explanation neither an example. Hence we even used the option `thesisinfoinnotes` so that the user could decide where to put the information about the thesis.
However with the latest version of the norm (ISO 690:2021(E)) that I started to study a little, I figured that there is now a small section (8.16.6) showing how a thesis is supposed to be printed. There also a clear example now that I added to our example bib file.
> Improvment: Thesis Entrytype

- iso.bbx
This might look scary, but I think there is no good reason to have all that complicated and code from the commands like `\mkdaterangefull` and so on completely copied to this package when all we want to do is modify one line of these commands.
> Improvement: Using xpatchcmd
